#!/bin/sh

# 1st parameter is absolute path to component source directory
# 2nd parameter is absolute path to component build directory
# 3rd parameter is path to Python QA directory

../../../run_tests.sh \
    /home/braun/src/gnuradio/gr-cs \
    /home/braun/src/gnuradio/gr-cs \
    .
