all:
	(cd ducpin;   $(MAKE))
	(cd grape;    $(MAKE))
	(cd rawxfer;  $(MAKE))
	(cd rest_rew; $(MAKE))
	(cd vrk;      $(MAKE))
	(cd vrmeme;   $(MAKE))

clean:
	(cd ducpin;   $(MAKE) clean)
	(cd grape;    $(MAKE) clean)
	(cd rawxfer;  $(MAKE) clean)
	(cd rest_rew; $(MAKE) clean)
	(cd vrk;      $(MAKE) clean)
	(cd vrmeme;   $(MAKE) clean)
