#ifndef INCLUDE_READER_MONITOR_VARS
#define INCLUDE_READER_MONITOR_VARS

#define QUERY_MSG 666

enum {DELIM, TARI, PW, RTCAL, RTCAL_PW, CMD, PWCK, IDLE, DATA  };
enum {READER_MSG, TAG_MSG, PWR_DWN, INVALID_RTCAL, INVALID_TRCAL, PWR_UP};
enum {OKAY, ERROR};

#endif 
