/* -*- c++ -*- */
/*
 * Copyright 2011 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 *
 * This file was modified by William Plishker in 2011 for the GNU Radio 
 * support package GRGPU.  See www.cgran.org/wiki/GRGPU for more details.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <grgpu_add_const_ff_cuda.h>
#include <gr_io_signature.h>
#include <stdio.h>

/*
 * Create a new instance of grgpu_add_const_ff_cuda and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
grgpu_add_const_ff_cuda_sptr 
grgpu_make_add_const_ff_cuda (float constant)
{
  return grgpu_add_const_ff_cuda_sptr (new grgpu_add_const_ff_cuda (constant));
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.  In this case, we accept
 * only 1 input and 1 output.
 */
static const int MIN_IN = 1;	// mininum number of input streams
static const int MAX_IN = 1;	// maximum number of input streams
static const int MIN_OUT = 1;	// minimum number of output streams
static const int MAX_OUT = 1;	// maximum number of output streams

/*
 * The private constructor
 */
grgpu_add_const_ff_cuda::grgpu_add_const_ff_cuda (float constant)
  : gr_block ("add_const_ff_cuda",
	      gr_make_io_signature (MIN_IN, MAX_IN, sizeof (unsigned long)),
	      gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (unsigned long)))
{
  context = (grgpu_add_const_ff_cuda_context*) malloc(sizeof(grgpu_add_const_ff_cuda_context));
  context->constant = constant;
}

/*
 * Our virtual destructor.
 */
grgpu_add_const_ff_cuda::~grgpu_add_const_ff_cuda ()
{
  // nothing else required in this example
}


/*
 * The C hook into our cuda kernel call
 */
void grgpu_add_const_ff_cuda_work_device(int noutput_items, const unsigned long* input_items, unsigned long* output_items, grgpu_add_const_ff_cuda_context* context);


int 
grgpu_add_const_ff_cuda::general_work (int noutput_items,
			       gr_vector_int &ninput_items,
			       gr_vector_const_void_star &input_items,
			       gr_vector_void_star &output_items)
{


  int i;
  printf("Executing Work function for add_const_ff_cuda.\n");
  const unsigned long *in = (const unsigned long *) input_items[0];
  unsigned long *out = (unsigned long *) output_items[0];


   
   printf("From general Work function, I/O: %ld, %ld , noutput:%d.\n", in[0], out[0], noutput_items);
   grgpu_add_const_ff_cuda_work_device(noutput_items, in, out, context);
   //   for ( i = 0; i < 10; ++i) {
   //	printf("Filter Output[%d]: %f.\n",i,  out[i]);
   //}
   //   scanf("%d", &i);

   consume_each (noutput_items);

  // Tell runtime system how many output items we produced.
  return noutput_items;
}
