#!/bin/bash

# Check parameter
if [ $# != 1 ] ; then
  echo "    Usage: $0 <path-to-GnuRadio-source-tree-root>"
  exit
fi

# Get root of GnuRadio 3.1.3 source tree
ROOTDIRPATH=$1

# Check it to be sure it's GnuRadio 3.1.3
NAME=`basename $ROOTDIRPATH`
if ! [[ $NAME =~ "gnuradio-3.1.3" ]] ; then
  echo
  echo "    Supplied path does not point to root of GnuRadio 3.1.3 source."
  echo "    This script can ONLY be applied to GnuRadio 3.1.3!!!"
  echo "    Install aborted."
  echo
  exit
fi

# Check for existence of ROOTDIRPATH
if ! [[ -d $ROOTDIRPATH ]]; then
  echo
  echo "    $ROOTDIRPATH does not exist or is not a directory."
  echo "    Install aborted."
  echo
  exit
fi

# Setup full path to gnuradio-core/src/lib/general
FULLPATH=$ROOTDIRPATH/gnuradio-core/src/lib/general

# Check if script has already been run
if ! [[ -e $FULLPATH/general.i.bak ]]; then
  echo
  echo "    Can't uninstall."
  echo "    The install script has not been previously run."
  echo "    Uninstall aborted."
  echo
  exit
fi

# Remove soft links to .cc , .h , and .i files in
# gnuradio-core/src/lib/general.
rm $FULLPATH/gr_derandomize_bb.[chi]*
rm $FULLPATH/gr_hdlc_router_sink_b.[chi]*
rm $FULLPATH/gr_hdlc_router_source_b.[chi]*
rm $FULLPATH/gr_nrzi_to_nrz_bb.[chi]*
rm $FULLPATH/gr_nrz_to_nrzi_bb.[chi]*
rm $FULLPATH/gr_randomize_bb.[chi]*
rm $FULLPATH/gr_digital_upsampler_bb.[chi]*

# Remove modified files
rm $FULLPATH/general.i
rm $FULLPATH/Makefile.am

# Restore from backup copies of general.i and Makefile.am
# in gnuradio-core/src/lib/general.
mv $FULLPATH/general.i.bak   $FULLPATH/general.i
mv $FULLPATH/Makefile.am.bak $FULLPATH/Makefile.am

# Touch them so make will redo dependencies next time
touch $FULLPATH/general.i
touch $FULLPATH/Makefile.am

# Done!
echo
echo "Uninstall completed."
echo "Now, cd to $ROOTDIRPATH and do:"
echo "   make"
echo "   make check"
echo "   sudo make install"
echo




