//
// Machine generated by compile-mbh from ./gmsk.mbh
//
// protocol-classes: gmsk-cs 
//
#include <mblock/protocol_class.h>
#include <unistd.h>
static const char
protocol_class_init_data[74] = {
  7, 2, 0, 7, 103, 109, 115, 107, 45, 99, 115, 7, 7, 2, 0, 12, 
  114, 101, 115, 112, 111, 110, 115, 101, 45, 109, 111, 100, 7, 2, 0, 14, 
  114, 101, 115, 112, 111, 110, 115, 101, 45, 100, 101, 109, 111, 100, 6, 7, 
  7, 2, 0, 7, 99, 109, 100, 45, 109, 111, 100, 7, 2, 0, 9, 99, 
  109, 100, 45, 100, 101, 109, 111, 100, 6, 6, 
};
static mb_protocol_class_init _init_(protocol_class_init_data, sizeof(protocol_class_init_data));
