/* -*- c++ -*- */
/*
 * Copyright 2011 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 *
 * This file was modified by William Plishker in 2011 for the GNU Radio 
 * support package GRGPU.  See www.cgran.org/wiki/GRGPU for more details.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <grgpu_fir_filter_fff_cuda.h>
#include <gr_io_signature.h>
#include <stdio.h>

/*
 * The C hook into our cuda kernel call
 */
//void grgpu_fir_filter_fff_cuda_work_device(int noutput_items, const unsigned long* input_items, unsigned long* output_items);

void grgpu_fir_filter_fff_cuda_work_device(int noutput_items, const unsigned long* input_items, unsigned long* output_items, void**d_taps, float*h_taps,int h_length, int verbose);



/*
 * Create a new instance of grgpu_fir_filter_fff_cuda and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
grgpu_fir_filter_fff_cuda_sptr 
grgpu_make_fir_filter_fff_cuda (const std::vector<float> &taps)
{
  return grgpu_fir_filter_fff_cuda_sptr (new grgpu_fir_filter_fff_cuda (taps));
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.  In this case, we accept
 * only 1 input and 1 output.
 */
static const int MIN_IN = 1;	// mininum number of input streams
static const int MAX_IN = 1;	// maximum number of input streams
static const int MIN_OUT = 1;	// minimum number of output streams
static const int MAX_OUT = 1;	// maximum number of output streams

/*
 * The private constructor
 */
grgpu_fir_filter_fff_cuda::grgpu_fir_filter_fff_cuda (const std::vector<float> &taps)
  : gr_block ("fir_filter_fff_cuda",
	      gr_make_io_signature (MIN_IN, MAX_IN, sizeof (unsigned long)),
	      gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (unsigned long)))
{
  length = taps.size();
  h_taps = (float*)malloc(sizeof(float)*length);
  for(int i=0; i<length; i++){
    h_taps[i] = taps[i];
  }
  d_taps = 0;
  verbose = 0;
}

void
grgpu_fir_filter_fff_cuda:: set_verbose(int v){ 
  verbose = v; 
}

/*
 * Our virtual destructor.
 */
grgpu_fir_filter_fff_cuda::~grgpu_fir_filter_fff_cuda ()
{
  // nothing else required in this example
}


int 
grgpu_fir_filter_fff_cuda::general_work (int noutput_items,
			       gr_vector_int &ninput_items,
			       gr_vector_const_void_star &input_items,
			       gr_vector_void_star &output_items)
{


  int i;
  if(verbose)
    printf("Executing Work function for fir_filter_fff_cuda.\n");

  const unsigned long *in = (const unsigned long *) input_items[0];
  unsigned long *out = (unsigned long *) output_items[0];


  if(verbose)
    printf("From general Work function, I/O: %ld, %ld , noutput:%d.\n", in[0], out[0], noutput_items);

  grgpu_fir_filter_fff_cuda_work_device(noutput_items, 
					in, 
					out,
					(void**)&d_taps,
					h_taps,
					length,
					verbose);


  consume_each (noutput_items);

  // Tell runtime system how many output items we produced.
  return noutput_items;
}
