/* -*- c++ -*- */
/*
 * Copyright 2011 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 *
 * This file was modified by William Plishker in 2011 for the GNU Radio 
 * support package GRGPU.  See www.cgran.org/wiki/GRGPU for more details. 
 */ 

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <grgpu_h2d_cuda.h>
#include <gr_io_signature.h>
#include <stdio.h>
#include <time.h>
/*
 * Create a new instance of grgpu_h2d_cuda and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
grgpu_h2d_cuda_sptr 
grgpu_make_h2d_cuda ()
{
  return grgpu_h2d_cuda_sptr (new grgpu_h2d_cuda ());
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.  In this case, we accept
 * only 1 input and 1 output.
 */
static const int MIN_IN = 1;	// mininum number of input streams
static const int MAX_IN = 1;	// maximum number of input streams
static const int MIN_OUT = 1;	// minimum number of output streams
static const int MAX_OUT = 1;	// maximum number of output streams

/*
 * The C hook into our cuda kernel call
 */
void grgpu_h2d_cuda_work_device(int noutput_items, const float* input_items, unsigned long* output_items, grgpu_fifo**context);
void grgpu_h2d_cuda_init_device(grgpu_fifo**context);

/*
 * The private constructor
 */
grgpu_h2d_cuda::grgpu_h2d_cuda ()
  : gr_block ("h2d_cuda",
	      gr_make_io_signature (MIN_IN, MAX_IN, sizeof (float)),
	      gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (unsigned long)))
{
  verbose = 0;
  hist = 0;
  multiple = 1;
  length = 100000*multiple*sizeof(float);
  context = (grgpu_fifo**)malloc(sizeof(void*));
  (*context) = (grgpu_fifo*)malloc(sizeof(grgpu_fifo));
  grgpu_fifo *fifo = *context;
  fifo->token_size = sizeof(float);
  fifo->history = hist;
  fifo->multiple = multiple;
  fifo->length = length;
  fifo->wrap_pad = 0;
  fifo->buffer = 0x0;
  this->set_output_multiple(fifo->multiple);
  printf("in constructor\n");
  grgpu_h2d_cuda_init_device(context);
}

/*
 * Our virtual destructor.
 */
grgpu_h2d_cuda::~grgpu_h2d_cuda ()
{
  // nothing else required in this example
}

int 
grgpu_h2d_cuda::general_work (int noutput_items,
			       gr_vector_int &ninput_items,
			       gr_vector_const_void_star &input_items,
			       gr_vector_void_star &output_items)
{
  int i;
  if(verbose)
    printf("Executing Work function for H2D.\n");
  const float *in = (const float *) input_items[0];
  unsigned long *out = (unsigned long *) output_items[0];

  if(verbose)
    printf("H2D %dms\n", clock()/1000);

  grgpu_h2d_cuda_work_device(noutput_items, in, out, context);
  if(verbose)
    printf("H2D, I/O: %f, %p , noutput:%d.\n", in[0], out[0], noutput_items);

  consume_each (noutput_items);

  return noutput_items;
}
